# TODO

1. NdBSpline: a tuple of non-zero b-spline vectors
2. *[DONE]* Tests with 2D
3. and 3D
4. *[DONE]* vector of `x`   + tests
5. *[DONE]* trailing dimensions of `c`: reshape, loop, reshape back + tests
6. get rid of `itertools.product` : iterate over c.flat (subarray!)
7. test mixed degrees: k = [2, 3] etc

In [1]:
def B(x, k, i, t):
    if k == 0:
        return 1.0 if t[i] <= x < t[i+1] else 0.0
    if t[i+k] == t[i]:
        c1 = 0.0
    else:
        c1 = (x - t[i])/(t[i+k] - t[i]) * B(x, k-1, i, t)
    if t[i+k+1] == t[i+1]:
        c2 = 0.0
    else:
        c2 = (t[i+k+1] - x)/(t[i+k+1] - t[i+1]) * B(x, k-1, i+1, t)
    return c1 + c2

def bspline(x, t, c, k):
    n = len(t) - k - 1
    assert (n >= k+1) and (len(c) >= n)
    return sum(c[i] * B(x, k, i, t) for i in range(n))

In [63]:
def _naive_eval(x, t, c, k):
    """
    Naive B-spline evaluation. Useful only for testing!
    """
    if x == t[k]:
        i = k
    else:
        i = np.searchsorted(t, x) - 1
    assert t[i] <= x <= t[i+1]
    assert i >= k and i < len(t) - k
    return sum(c[i-j] * B(x, k, i-j, t) for j in range(0, k+1))

In [65]:
_naive_eval(1.5, spl.t, spl.c, 3), spl(1.5)

(3.3749999999999996, array(3.375))

In [80]:
import numpy as np
from scipy.interpolate import make_interp_spline

def prod(iterable):
    """
    Product of a sequence of numbers.

    Faster than np.prod for short lists like array shapes, and does
    not overflow if using Python integers.
    """
    product = 1
    for x in iterable:
        product *= x
    return product

In [164]:
x = np.arange(6)
y = x**3
spl = make_interp_spline(x, y, k=3)

In [7]:
spl.t

array([0., 0., 0., 0., 2., 3., 5., 5., 5., 5.])

In [10]:
spl.c

array([ 0.00000000e+00, -8.11457125e-16,  1.61091184e-15,  3.00000000e+01,
        7.50000000e+01,  1.25000000e+02])

In [165]:
y_1 = x**3 + 2*x
spl_1 = make_interp_spline(x, y_1, k=3)
spl_1.t, spl_1.c

(array([0., 0., 0., 0., 2., 3., 5., 5., 5., 5.]),
 array([  0.        ,   1.33333333,   3.33333333,  36.66666667,
         83.66666667, 135.        ]))

In [287]:
# make the outer product of 1D coefficients

c2 = np.outer(spl_1.c, spl.c)

with np.printoptions(suppress=True, linewidth=100):
    print(c2)

[[    0.            -0.             0.             0.             0.             0.        ]
 [    0.            -0.             0.            40.           100.           166.66666667]
 [    0.            -0.             0.           100.           250.           416.66666667]
 [    0.            -0.             0.          1100.          2750.          4583.33333333]
 [    0.            -0.             0.          2510.          6275.         10458.33333333]
 [    0.            -0.             0.          4050.         10125.         16875.        ]]


In [29]:
def bspline2(xy, t, c, k):
    x, y = xy
    tx, ty = t
    nx = len(tx) - k - 1
    assert (nx >= k+1)
    ny = len(ty) - k - 1
    assert (ny >= k+1)
    return sum(c[ix, iy] * B(x, k, ix, tx) * B(y, k, iy, ty) for ix in range(nx) for iy in range(ny))

In [34]:
for x0, y0 in [(1.5, 0.5), (2.5, 1), (0.5, 1.5)]:
    print((x0**3 + 2*x0)* y0**3, ' -- ',
          bspline2((x0, y0), (spl.t, spl_1.t), c2, k=3))

0.796875  --  0.7968749999999984
20.625  --  20.625
3.796875  --  3.796875000000001


In [25]:
(0.5**3 + 2*0.5) * 1.5**3

3.796875

In [150]:
class NdBSpline0:
    def __init__(self, t, c, k=3):
        """Tensor product spline object.
        
        c[i1, i2, ..., id] * B(x1, i1) * B(x2, i2) * ... * B(xd, id)
        
        
        Parameters
        ----------
        c : ndarray, shape (n1, n2, ..., nd, ...)
            b-spline coefficients
        t : tuple of 1D ndarrays
            knot vectors in directions 1, 2, ... d
            ``len(t[i]) == n[i] + k + 1``
        k : int or length-d tuple of integers
            spline degrees.
        """
        ndim = len(t)
        assert ndim <= len(c.shape)
        
        try:
            len(k)
        except TypeError:
            # make k a tuple
            k = (k,)*ndim

        self.k = tuple(operator.index(ki) for ki in k)
        self.t = tuple(np.asarray(ti, dtype=float) for ti in t)
        self.c = c

    def __call__(self, x):
        ndim = len(self.t)
        # a single evaluation point: `x` is a 1D array_like, shape (ndim,)
        assert len(x) == ndim
        
        # get the indices in an ndim-dimensional vector
        i = ['none',]*ndim
        for d in range(ndim):
            td, xd = self.t[d], x[d]
            k = self.k[d]
            
            # find the index for x[d]
            if xd == td[k]:
                i[d] = k
            else:
                i[d] = np.searchsorted(td, xd) - 1
            assert td[i[d]] <= xd <= td[i[d]+1]
            assert i[d] >= k and i[d] < len(td) - k
        i = tuple(i)
        
        # iterate over the dimensions, form linear combinations of
        # products B(x_1) * B(x_2) * ... B(x_N) of (k+1)**N b-splines
        # which are non-zero at `i = (i_1, i_2, ..., i_N)`.
        result = 0
        iters = [range(i[d] - self.k[d], i[d] + 1) for d in range(ndim)]
        for idx in itertools.product(*iters):
            term = self.c[idx] * prod(B(x[d], self.k[d], idx[d], self.t[d]) for d in range(ndim))
            result += term
        return result

In [438]:
class NdBSpline:
    """Tensor product spline object.

    c[i1, i2, ..., id] * B(x1, i1) * B(x2, i2) * ... * B(xd, id)


    Parameters
    ----------
    c : ndarray, shape (n1, n2, ..., nd, ...)
        b-spline coefficients
    t : tuple of 1D ndarrays
        knot vectors in directions 1, 2, ... d
        ``len(t[i]) == n[i] + k + 1``
    k : int or length-d tuple of integers
        spline degrees.
    """
    def __init__(self, t, c, k=3):
        ndim = len(t)
        assert ndim <= len(c.shape)
        
        try:
            len(k)
        except TypeError:
            # make k a tuple
            k = (k,)*ndim

        self.k = tuple(operator.index(ki) for ki in k)
        self.t = tuple(np.asarray(ti, dtype=float) for ti in t)
        self.c = c

    def __call__(self, xi):
        """Evaluate the tensor product b-spline at coordinates.
        
        Parameters
        ----------
        xi : array_like, shape(..., ndim)
            The coordinates to evaluate the interpolator at.
            This can be a list or tuple of ndim-dimensional points
            or an array with the shape (num_points, ndim).
            
        Returns
        -------
        values : ndarray, shape xi.shape[:-1] + self.c.shape[ndim:]
            Interpolated values at xi
        """
        ndim = len(self.t)

        # prepare xi : shape (..., m1, ..., md) -> (1, m1, ..., md)
        xi = np.asarray(xi, dtype=float)
        xi_shape = xi.shape
        xi = xi.reshape(-1, xi_shape[-1])        
        xi = np.ascontiguousarray(xi)

        if xi_shape[-1] != ndim:
            raise ValueError(f"Shapes: xi.shape={xi_shape} and ndim={ndim}")
        
        # prepare the coefficients: flatten the trailing dimensions
        c1 = self.c.reshape(self.c.shape[:ndim] + (-1,))
        
        num_c_tr = c1.shape[-1]  # # of trailing coefficients
        out = np.empty(xi.shape[:-1] + (num_c_tr,), dtype=float)
        
        # iterate over the data points
        for j in range(xi.shape[0]):
            x = xi[j]
            
            # get the indices in an ndim-dimensional vector
            i = ['none',]*ndim
            b = np.empty((ndim, max(self.k)+1), dtype=float) * np.nan
            for d in range(ndim):
                td, xd = self.t[d], x[d]
                k = self.k[d]

                # find the index for x[d]
                if xd == td[k]:
                    i[d] = k
                else:
                    i[d] = np.searchsorted(td, xd) - 1
                assert td[i[d]] <= xd <= td[i[d]+1]
                assert i[d] >= k and i[d] < len(td) - k

                # (k+1) b-splines which are non-zero at x[d] 
                b[d, :k+1] = [B(xd, k, j, td) for j in range(i[d]-k, i[d]+1)]   
            i = tuple(i)

            # iterate over the dimensions, form linear combinations of
            # products B(x_1) * B(x_2) * ... B(x_N) of (k+1)**N b-splines
            # which are non-zero at `i = (i_1, i_2, ..., i_N)`.
            result = np.zeros(num_c_tr, dtype=float)
            iters = [range(i[d] - self.k[d], i[d] + 1) for d in range(ndim)]
            for idx in itertools.product(*iters):
                factor = prod(b[d, idx[d] - i[d] + k] for d in range(ndim))
                # loop over the trailing values of self.c explicitly
                for i_c in range(num_c_tr):
                    result[i_c] += c1[idx + (i_c,)] * factor

            # copy the result over: this is in fact a loop over num_c_tr
            out[j, ...] = result
            
        return out.reshape(xi_shape[:-1] + self.c.shape[ndim:])

In [399]:
bspl2 = NdBSpline((spl.t, spl_1.t), c2, k=3)

for x0, y0 in [(1.5, 2.5), (2.5, 1), (0.5, 1.5)]:
    print((x0**3 + 2*x0)* y0**3, ' -- ',
          bspline2((x0, y0), (spl.t, spl_1.t), c2, k=3), '--',
         ## naive_B_2((x0, y0), (spl.t, spl_1.t), c2, k=3), )
          bspl2((x0, y0))
         )

(6, 6, 1)
99.609375  --  99.60937499999999 -- 99.60937499999997
(6, 6, 1)
20.625  --  20.625 -- 20.625
(6, 6, 1)
3.796875  --  3.796875000000001 -- 3.796875000000001


In [271]:
bspl2([(1.5, 2.5), (2.5, 1), (0.5, 1.5)])

array([99.609375, 20.625   ,  3.796875])

In [207]:
spl2 = NdBSpline((spl.t, spl_1.t), c2, k=3)

spl2((1.5, 2.5))

99.60937499999997

In [108]:
spl.t, spl_1.t

(array([0., 0., 0., 0., 2., 3., 5., 5., 5., 5.]),
 array([0., 0., 0., 0., 2., 3., 5., 5., 5., 5.]))

In [314]:
k = 3
p = itertools.product(*(range(0, k+1),)*3)
for j, tpl in enumerate(p):
    #print(j, tpl, a[tpl])
    pass

# Tests

In [281]:
def bspline2(xy, t, c, k):
    """A naive 2D tensort product spline evaluation."""
    x, y = xy
    tx, ty = t
    nx = len(tx) - k - 1
    assert (nx >= k+1)
    ny = len(ty) - k - 1
    assert (ny >= k+1)
    return sum(c[ix, iy] * B(x, k, ix, tx) * B(y, k, iy, ty) for ix in range(nx) for iy in range(ny))


def naive_B_2(xy, t, c, k):
    """
    Naive B-spline evaluation, another way.
    """
    x, y = xy
    tx, ty = t
    
    if x == tx[k]:
        ix = k
    else:
        ix = np.searchsorted(tx, x) - 1
    assert tx[ix] <= x <= tx[ix + 1]
    assert ix >= k and ix < len(tx) - k

    if y == ty[k]:
        iy = k
    else:
        iy = np.searchsorted(ty, y) - 1
    assert ty[iy] <= y <= ty[iy + 1]
    assert iy >= k and iy < len(ty) - k
    
    res = sum(c[ix-jx, iy - jy] * B(x, k, ix-jx, tx) * B(y, k, iy-jy, ty)
               for jx in range(0, k+1) for jy in range(0, k+1))
    
    result = 0
    for jx in range(ix-k, ix+1):
        for jy in range(iy-k, iy+1):
#            print(jx, ix - jx)
            result += c[jx, jy] * B(x, k, jx, tx) * B(y, k, jy, ty)
            
    assert np.allclose(result,  res) #, result-res
    return result

In [293]:
from numpy.testing import assert_allclose
from numpy.random import default_rng


def make_2d_case():
    # make a 2D separable spline
    x = np.arange(6)
    y = x**3
    spl = make_interp_spline(x, y, k=3)
    
    y_1 = x**3 + 2*x
    spl_1 = make_interp_spline(x, y_1, k=3)

    t2 = (spl.t, spl_1.t)
    c2 = np.outer(spl_1.c, spl.c)
    
    return t2, c2, 3

In [446]:
# test 2D

def test_2D_separable():
    xi = [(1.5, 2.5), (2.5, 1), (0.5, 1.5)]  
    t2, c2, k = make_2d_case()
    target = [(x**3 + 2*x) * y**3 for (x, y) in xi]
    
    # sanity check: bspline2 gives the product as constructed
    assert_allclose([bspline2(xy, t2, c2, k) for xy in xi],
                    target,
                    atol=1e-14)

    # check evaluation on a 2D array: the 1D array of 2D points
    bspl2 = NdBSpline(t2, c2, k=3)
    assert bspl2(xi).shape == (len(xi), )
    assert_allclose(bspl2(xi),
                    target, atol=1e-14)
    
    # now check on a multidim xi
    rng = default_rng(12345)
    xi = rng.uniform(size=(4, 3, 2)) * 5
    result = bspl2(xi)
    assert result.shape == (4, 3)
    
    # also check the values
    x, y = xi.reshape((-1, 2)).T
    assert_allclose(result.ravel(),
                    (x**3 + 2*x) * y**3, atol=1e-14)


def test_2D_separable_2():
    # test `c` with trailing dimensions, i.e. c.ndim > ndim
    ndim = 2
    xi = [(1.5, 2.5), (2.5, 1), (0.5, 1.5)]  
    target = [(x**3 + 2*x) * y**3 for (x, y) in xi]

    t2, c2, k = make_2d_case()
    c2_4 = np.dstack((c2, c2, c2, c2))   # c22.shape = (6, 6, 4)

    xy = (1.5, 2.5)
    bspl2_4 = NdBSpline(t2, c2_4, k=3)
    val_single = bspl2(xy)
    result = bspl2_4(xy)
    assert result.shape == (4,)
    assert_allclose(result,
                    [val_single,]*4, atol=1e-14)
    
    # now try the array xi : the output.shape is (3, 4)
    # where 3 is the number of points in xi and 4 is the trailing dimension of c
    assert bspl2_4(xi).shape == np.shape(xi)[:-1] + bspl2_4.c.shape[ndim:]
    assert_allclose(bspl2_4(xi) - np.asarray(target)[:, None],
                    0, atol=5e-14)
    
    # two trailing dimensions
    c2_22 = c2_4.reshape((6, 6, 2, 2))
    bspl2_22 = NdBSpline(t2, c2_22, k=3)
    
    result = bspl2_22(xy)
    assert result.shape == (2, 2)
    assert_allclose(result,
                    [[val_single, val_single],
                     [val_single, val_single]], atol=1e-14)

    # now try the array xi : the output shape is (3, 2, 2)
    # for 3 points in xi and c trailing dimensions being (2, 2)
    assert bspl2_22(xi).shape == np.shape(xi)[:-1] + bspl2_22.c.shape[ndim:]
    assert_allclose(bspl2_22(xi) - np.asarray(target)[:, None, None],
                    0, atol=5e-14)
    
#### RUN test ###
    
test_2D_separable()
test_2D_separable_2()

(6, 6, 1)


In [345]:
# test 3D  : FIXME

def make_3d_case():
    # make a 3D separable spline
    x = np.arange(6)
    y = x**3
    spl = make_interp_spline(x, y, k=3)
    
    y_1 = x**3 + 2*x
    spl_1 = make_interp_spline(x, y_1, k=3)

    y_2 = x**3 + 3*x + 1
    spl_2 = make_interp_spline(x, y_2, k=3)
    
    
    t2 = (spl.t, spl_1.t, spl_2.t)
    c2 = np.outer(spl_2.c, spl_1.c, spl.c)
    
    return t2, c2, 3

def test_3D_separable():
    xi = [(1.5, 2.5), (2.5, 1), (0.5, 1.5)]  
    t2, c2, k = make_2d_case()
    target = [(x**3 + 2*x) * y**3 for (x, y) in xi]
    
    # sanity check: bspline2 gives the product as constructed
    assert_allclose([bspline2(xy, t2, c2, k) for xy in xi],
                    target,
                    atol=1e-14)

    # check evaluation on a 2D array: the 1D array of 2D points
    bspl2 = NdBSpline(t2, c2, k=3)
    assert bspl2(xi).shape == (len(xi), )
    assert_allclose(bspl2(xi),
                    target, atol=1e-14)
    
    # now check on a multidim xi
    rng = default_rng(12345)
    xi = rng.uniform(size=(4, 3, 2)) * 5
    result = bspl2(xi)
    assert result.shape == (4, 3)
    
    # also check the values
    x, y = xi.reshape((-1, 2)).T
    assert_allclose(result.ravel(),
                    (x**3 + 2*x) * y**3, atol=1e-14)
    
test_2D_separable()

In [346]:
t2, c2, _ = make_3d_case()

ValueError: non-broadcastable output operand with shape (6,) doesn't match the broadcast shape (6,6)

In [357]:
x, y, z = np.array([1, 2, 3, 4]), np.array([4, 5, 6, 7, 8]), np.array([0.5, 1., 1.5])
np.outer(x, y)

array([[ 4,  5,  6,  7,  8],
       [ 8, 10, 12, 14, 16],
       [12, 15, 18, 21, 24],
       [16, 20, 24, 28, 32]])

In [362]:
(x[:, None] * y[None, :]).shape

(4, 5)

In [363]:
(x[:, None, None] * y[None, :, None] * z[None, None, :]).shape

(4, 5, 3)